# Default values for account.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

Account:
  name: account
  app: account
  replicaCount: 1
  containername: server
  containerPort: 50050
  image:
    repository: hme000/account
    tag: latest
    pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  name: account
  type: ClusterIP
  port: 50050
  targetport: 50050

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
