# Default values for db.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

db:
  name: db
  app: db
  replicaCount: 1
  containername: db
  containerPort: 3306
  image:
    repository: hme000/hme1
    tag: db
    pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  name: db
  type: None
  port: 3306

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}


nodeSelector: {}

tolerations: []

affinity: {}
