kind: pipeline
name: default

workspace:
  path: ./src/Frontend

steps:
- name: docker
  image: plugins/docker
  settings:
    username: hme000
    password: Infy_4321
    repo: hme000/hme1
    dockerfile: ./src/Frontend/Dockerfile
    tags:
      - latest
    when:
      event: push
      branch: master