# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import account_pb2 as account__pb2

class AccountServiceStub(object):
  """-----------------Account Service-----------------
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.register = channel.unary_unary(
        '/demojam2019.AccountService/register',
        request_serializer=account__pb2.RegisterRequest.SerializeToString,
        response_deserializer=account__pb2.RegisterResponse.FromString,
        )
    self.login = channel.unary_unary(
        '/demojam2019.AccountService/account',
        request_serializer=account__pb2.LoginRequest.SerializeToString,
        response_deserializer=account__pb2.LoginResponse.FromString,
        )


class AccountServiceServicer(object):
  """-----------------Account Service-----------------
  """

  def register(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def login(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AccountServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'register': grpc.unary_unary_rpc_method_handler(
          servicer.register,
          request_deserializer=account__pb2.RegisterRequest.FromString,
          response_serializer=account__pb2.RegisterResponse.SerializeToString,
      ),
      'account': grpc.unary_unary_rpc_method_handler(
          servicer.login,
          request_deserializer=account__pb2.LoginRequest.FromString,
          response_serializer=account__pb2.LoginResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'demojam2019.AccountService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
