# Default values for asset.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

Asset:
  name: asset
  app: asset
  replicaCount: 1
  containername: asset
  containerPort: 50051
  image:
    repository: hme000/hme1
    tag: asset
    pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  name: assetcreation
  type: ClusterIP
  port: 50051
  targetPort: 50051

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
