apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
{{ include "db.labels" . | indent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      name: web
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "db.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
