# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import db_pb2 as db__pb2


class DBServiceStub(object):
  """-----------------Db Service-----------------
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.register = channel.unary_unary(
        '/demojam2019.DBService/register',
        request_serializer=db__pb2.RegisterRequest.SerializeToString,
        response_deserializer=db__pb2.RegisterResponse.FromString,
        )
    self.login = channel.unary_unary(
        '/demojam2019.DBService/login',
        request_serializer=db__pb2.LoginRequest.SerializeToString,
        response_deserializer=db__pb2.LoginResponse.FromString,
        )
    self.addlog = channel.unary_unary(
        '/demojam2019.DBService/addlog',
        request_serializer=db__pb2.api_log.SerializeToString,
        response_deserializer=db__pb2.db_log.FromString,
        )


class DBServiceServicer(object):
  """-----------------Db Service-----------------
  """

  def register(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def login(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def addlog(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DBServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'register': grpc.unary_unary_rpc_method_handler(
          servicer.register,
          request_deserializer=db__pb2.RegisterRequest.FromString,
          response_serializer=db__pb2.RegisterResponse.SerializeToString,
      ),
      'login': grpc.unary_unary_rpc_method_handler(
          servicer.login,
          request_deserializer=db__pb2.LoginRequest.FromString,
          response_serializer=db__pb2.LoginResponse.SerializeToString,
      ),
      'addlog': grpc.unary_unary_rpc_method_handler(
          servicer.addlog,
          request_deserializer=db__pb2.api_log.FromString,
          response_serializer=db__pb2.db_log.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'demojam2019.DBService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
