# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import db_pb2 as db__pb2


class DBServiceStub(object):
  """-----------------Db Service-----------------
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.register_db = channel.unary_unary(
        '/demojam2019.DBService/register_db',
        request_serializer=db__pb2.RegisterRequest_db.SerializeToString,
        response_deserializer=db__pb2.RegisterResponse_db.FromString,
        )
    self.login_db = channel.unary_unary(
        '/demojam2019.DBService/login_db',
        request_serializer=db__pb2.LoginRequest_db.SerializeToString,
        response_deserializer=db__pb2.LoginResponse_db.FromString,
        )
    self.addlog_db = channel.unary_unary(
        '/demojam2019.DBService/addlog_db',
        request_serializer=db__pb2.api_log_db.SerializeToString,
        response_deserializer=db__pb2.db_log_db.FromString,
        )


class DBServiceServicer(object):
  """-----------------Db Service-----------------
  """

  def register_db(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def login_db(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def addlog_db(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DBServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'register_db': grpc.unary_unary_rpc_method_handler(
          servicer.register_db,
          request_deserializer=db__pb2.RegisterRequest_db.FromString,
          response_serializer=db__pb2.RegisterResponse_db.SerializeToString,
      ),
      'login_db': grpc.unary_unary_rpc_method_handler(
          servicer.login_db,
          request_deserializer=db__pb2.LoginRequest_db.FromString,
          response_serializer=db__pb2.LoginResponse_db.SerializeToString,
      ),
      'addlog_db': grpc.unary_unary_rpc_method_handler(
          servicer.addlog_db,
          request_deserializer=db__pb2.api_log_db.FromString,
          response_serializer=db__pb2.db_log_db.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'demojam2019.DBService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
