# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: db.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='db.proto',
  package='demojam2019',
  syntax='proto3',
  serialized_options=_b('\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW'),
  serialized_pb=_b('\n\x08\x64\x62.proto\x12\x0b\x64\x65mojam2019\"p\n\x12RegisterRequest_db\x12\x12\n\nuser_id_db\x18\x01 \x01(\t\x12\x14\n\x0cuser_name_db\x18\x02 \x01(\t\x12\x13\n\x0bpassword_db\x18\x03 \x01(\t\x12\x1b\n\x13password_confirm_db\x18\x04 \x01(\t\"?\n\x13RegisterResponse_db\x12\x12\n\nuser_id_db\x18\x01 \x01(\t\x12\x14\n\x0cuser_name_db\x18\x02 \x01(\t\":\n\x0fLoginRequest_db\x12\x12\n\nuser_id_db\x18\x01 \x01(\t\x12\x13\n\x0bpassword_db\x18\x02 \x01(\t\"(\n\x10LoginResponse_db\x12\x14\n\x0cuser_name_db\x18\x01 \x01(\t\"\x1d\n\napi_log_db\x12\x0f\n\x07text_db\x18\x01 \x01(\t\"\x1c\n\tdb_log_db\x12\x0f\n\x07text_db\x18\x01 \x01(\t2\xea\x01\n\tDBService\x12R\n\x0bregister_db\x12\x1f.demojam2019.RegisterRequest_db\x1a .demojam2019.RegisterResponse_db\"\x00\x12I\n\x08login_db\x12\x1c.demojam2019.LoginRequest_db\x1a\x1d.demojam2019.LoginResponse_db\"\x00\x12>\n\taddlog_db\x12\x17.demojam2019.api_log_db\x1a\x16.demojam2019.db_log_db\"\x00\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)




_REGISTERREQUEST_DB = _descriptor.Descriptor(
  name='RegisterRequest_db',
  full_name='demojam2019.RegisterRequest_db',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id_db', full_name='demojam2019.RegisterRequest_db.user_id_db', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_name_db', full_name='demojam2019.RegisterRequest_db.user_name_db', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password_db', full_name='demojam2019.RegisterRequest_db.password_db', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password_confirm_db', full_name='demojam2019.RegisterRequest_db.password_confirm_db', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=137,
)


_REGISTERRESPONSE_DB = _descriptor.Descriptor(
  name='RegisterResponse_db',
  full_name='demojam2019.RegisterResponse_db',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id_db', full_name='demojam2019.RegisterResponse_db.user_id_db', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_name_db', full_name='demojam2019.RegisterResponse_db.user_name_db', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=202,
)


_LOGINREQUEST_DB = _descriptor.Descriptor(
  name='LoginRequest_db',
  full_name='demojam2019.LoginRequest_db',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id_db', full_name='demojam2019.LoginRequest_db.user_id_db', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password_db', full_name='demojam2019.LoginRequest_db.password_db', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=262,
)


_LOGINRESPONSE_DB = _descriptor.Descriptor(
  name='LoginResponse_db',
  full_name='demojam2019.LoginResponse_db',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_name_db', full_name='demojam2019.LoginResponse_db.user_name_db', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=304,
)


_API_LOG_DB = _descriptor.Descriptor(
  name='api_log_db',
  full_name='demojam2019.api_log_db',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text_db', full_name='demojam2019.api_log_db.text_db', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=306,
  serialized_end=335,
)


_DB_LOG_DB = _descriptor.Descriptor(
  name='db_log_db',
  full_name='demojam2019.db_log_db',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text_db', full_name='demojam2019.db_log_db.text_db', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=337,
  serialized_end=365,
)

DESCRIPTOR.message_types_by_name['RegisterRequest_db'] = _REGISTERREQUEST_DB
DESCRIPTOR.message_types_by_name['RegisterResponse_db'] = _REGISTERRESPONSE_DB
DESCRIPTOR.message_types_by_name['LoginRequest_db'] = _LOGINREQUEST_DB
DESCRIPTOR.message_types_by_name['LoginResponse_db'] = _LOGINRESPONSE_DB
DESCRIPTOR.message_types_by_name['api_log_db'] = _API_LOG_DB
DESCRIPTOR.message_types_by_name['db_log_db'] = _DB_LOG_DB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegisterRequest_db = _reflection.GeneratedProtocolMessageType('RegisterRequest_db', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERREQUEST_DB,
  '__module__' : 'db_pb2'
  # @@protoc_insertion_point(class_scope:demojam2019.RegisterRequest_db)
  })
_sym_db.RegisterMessage(RegisterRequest_db)

RegisterResponse_db = _reflection.GeneratedProtocolMessageType('RegisterResponse_db', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERRESPONSE_DB,
  '__module__' : 'db_pb2'
  # @@protoc_insertion_point(class_scope:demojam2019.RegisterResponse_db)
  })
_sym_db.RegisterMessage(RegisterResponse_db)

LoginRequest_db = _reflection.GeneratedProtocolMessageType('LoginRequest_db', (_message.Message,), {
  'DESCRIPTOR' : _LOGINREQUEST_DB,
  '__module__' : 'db_pb2'
  # @@protoc_insertion_point(class_scope:demojam2019.LoginRequest_db)
  })
_sym_db.RegisterMessage(LoginRequest_db)

LoginResponse_db = _reflection.GeneratedProtocolMessageType('LoginResponse_db', (_message.Message,), {
  'DESCRIPTOR' : _LOGINRESPONSE_DB,
  '__module__' : 'db_pb2'
  # @@protoc_insertion_point(class_scope:demojam2019.LoginResponse_db)
  })
_sym_db.RegisterMessage(LoginResponse_db)

api_log_db = _reflection.GeneratedProtocolMessageType('api_log_db', (_message.Message,), {
  'DESCRIPTOR' : _API_LOG_DB,
  '__module__' : 'db_pb2'
  # @@protoc_insertion_point(class_scope:demojam2019.api_log_db)
  })
_sym_db.RegisterMessage(api_log_db)

db_log_db = _reflection.GeneratedProtocolMessageType('db_log_db', (_message.Message,), {
  'DESCRIPTOR' : _DB_LOG_DB,
  '__module__' : 'db_pb2'
  # @@protoc_insertion_point(class_scope:demojam2019.db_log_db)
  })
_sym_db.RegisterMessage(db_log_db)


DESCRIPTOR._options = None

_DBSERVICE = _descriptor.ServiceDescriptor(
  name='DBService',
  full_name='demojam2019.DBService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=368,
  serialized_end=602,
  methods=[
  _descriptor.MethodDescriptor(
    name='register_db',
    full_name='demojam2019.DBService.register_db',
    index=0,
    containing_service=None,
    input_type=_REGISTERREQUEST_DB,
    output_type=_REGISTERRESPONSE_DB,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='login_db',
    full_name='demojam2019.DBService.login_db',
    index=1,
    containing_service=None,
    input_type=_LOGINREQUEST_DB,
    output_type=_LOGINRESPONSE_DB,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='addlog_db',
    full_name='demojam2019.DBService.addlog_db',
    index=2,
    containing_service=None,
    input_type=_API_LOG_DB,
    output_type=_DB_LOG_DB,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DBSERVICE)

DESCRIPTOR.services_by_name['DBService'] = _DBSERVICE

# @@protoc_insertion_point(module_scope)
