# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: createAsset.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='createAsset.proto',
  package='asset',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11\x63reateAsset.proto\x12\x05\x61sset\"H\n\x05\x61sset\x12\x14\n\x0c\x63ompany_code\x18\x01 \x01(\t\x12\x14\n\x0c\x61sset_number\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"5\n\x03log\x12\x0f\n\x07\x61pi_log\x18\x01 \x01(\t\x12\x0e\n\x06\x64\x62_log\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"\x17\n\x07\x61pi_log\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x16\n\x06\x64\x62_log\x12\x0c\n\x04text\x18\x01 \x01(\t2*\n\x04\x43RUD\x12\"\n\x06\x63reate\x12\x0c.asset.asset\x1a\n.asset.log2-\n\x02\x44\x42\x12\'\n\x06update\x12\x0e.asset.api_log\x1a\r.asset.db_logb\x06proto3')
)




_ASSET = _descriptor.Descriptor(
  name='asset',
  full_name='asset.asset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='company_code', full_name='asset.asset.company_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='asset_number', full_name='asset.asset.asset_number', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='asset.asset.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=100,
)


_LOG = _descriptor.Descriptor(
  name='log',
  full_name='asset.log',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='api_log', full_name='asset.log.api_log', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='db_log', full_name='asset.log.db_log', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='asset.log.error', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=155,
)


_API_LOG = _descriptor.Descriptor(
  name='api_log',
  full_name='asset.api_log',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='asset.api_log.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=180,
)


_DB_LOG = _descriptor.Descriptor(
  name='db_log',
  full_name='asset.db_log',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='asset.db_log.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=204,
)

DESCRIPTOR.message_types_by_name['asset'] = _ASSET
DESCRIPTOR.message_types_by_name['log'] = _LOG
DESCRIPTOR.message_types_by_name['api_log'] = _API_LOG
DESCRIPTOR.message_types_by_name['db_log'] = _DB_LOG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

asset = _reflection.GeneratedProtocolMessageType('asset', (_message.Message,), {
  'DESCRIPTOR' : _ASSET,
  '__module__' : 'createAsset_pb2'
  # @@protoc_insertion_point(class_scope:asset.asset)
  })
_sym_db.RegisterMessage(asset)

log = _reflection.GeneratedProtocolMessageType('log', (_message.Message,), {
  'DESCRIPTOR' : _LOG,
  '__module__' : 'createAsset_pb2'
  # @@protoc_insertion_point(class_scope:asset.log)
  })
_sym_db.RegisterMessage(log)

api_log = _reflection.GeneratedProtocolMessageType('api_log', (_message.Message,), {
  'DESCRIPTOR' : _API_LOG,
  '__module__' : 'createAsset_pb2'
  # @@protoc_insertion_point(class_scope:asset.api_log)
  })
_sym_db.RegisterMessage(api_log)

db_log = _reflection.GeneratedProtocolMessageType('db_log', (_message.Message,), {
  'DESCRIPTOR' : _DB_LOG,
  '__module__' : 'createAsset_pb2'
  # @@protoc_insertion_point(class_scope:asset.db_log)
  })
_sym_db.RegisterMessage(db_log)



_CRUD = _descriptor.ServiceDescriptor(
  name='CRUD',
  full_name='asset.CRUD',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=206,
  serialized_end=248,
  methods=[
  _descriptor.MethodDescriptor(
    name='create',
    full_name='asset.CRUD.create',
    index=0,
    containing_service=None,
    input_type=_ASSET,
    output_type=_LOG,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CRUD)

DESCRIPTOR.services_by_name['CRUD'] = _CRUD


_DB = _descriptor.ServiceDescriptor(
  name='DB',
  full_name='asset.DB',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=250,
  serialized_end=295,
  methods=[
  _descriptor.MethodDescriptor(
    name='update',
    full_name='asset.DB.update',
    index=0,
    containing_service=None,
    input_type=_API_LOG,
    output_type=_DB_LOG,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DB)

DESCRIPTOR.services_by_name['DB'] = _DB

# @@protoc_insertion_point(module_scope)
