# Default values for frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

Frontend:
  name: frontend
  app: frontend
  replicaCount: 1
  containername: server
  containerPort: 5000
  image:
    repository: hme000/hme1
    tag: frontend
    pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  name: frontend
  type: LoadBalancer
  port: 1233
  targetport: 5000

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
