# Default values for db-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

DB:
  name: db-server
  app: db-server
  replicaCount: 1
  containername: server
  containerPort: 8001
  image:
    repository: hme000/db-server
    tag: latest
    pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  name: db-server
  type: ClusterIP
  port: 8001
  targetport: 8001

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
