# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import createAsset_pb2 as createAsset__pb2


class s4apiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.create = channel.unary_unary(
        '/asset.s4api/create',
        request_serializer=createAsset__pb2.assetInputs.SerializeToString,
        response_deserializer=createAsset__pb2.log.FromString,
        )
    self.display = channel.unary_unary(
        '/asset.s4api/display',
        request_serializer=createAsset__pb2.assetNumber.SerializeToString,
        response_deserializer=createAsset__pb2.assetResponse.FromString,
        )


class s4apiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def create(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def display(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_s4apiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'create': grpc.unary_unary_rpc_method_handler(
          servicer.create,
          request_deserializer=createAsset__pb2.assetInputs.FromString,
          response_serializer=createAsset__pb2.log.SerializeToString,
      ),
      'display': grpc.unary_unary_rpc_method_handler(
          servicer.display,
          request_deserializer=createAsset__pb2.assetNumber.FromString,
          response_serializer=createAsset__pb2.assetResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'asset.s4api', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class DBapiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.update = channel.unary_unary(
        '/asset.DBapi/update',
        request_serializer=createAsset__pb2.api_log.SerializeToString,
        response_deserializer=createAsset__pb2.db_log.FromString,
        )


class DBapiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def update(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DBapiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'update': grpc.unary_unary_rpc_method_handler(
          servicer.update,
          request_deserializer=createAsset__pb2.api_log.FromString,
          response_serializer=createAsset__pb2.db_log.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'asset.DBapi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
