# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: createAsset.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='createAsset.proto',
  package='asset',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11\x63reateAsset.proto\x12\x05\x61sset\"\x1c\n\x0b\x61ssetNumber\x12\r\n\x05value\x18\x01 \x01(\t\"N\n\x0b\x61ssetInputs\x12\x14\n\x0c\x63ompany_code\x18\x01 \x01(\t\x12\x14\n\x0c\x61sset_number\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"]\n\rassetResponse\x12\x14\n\x0c\x63ompany_code\x18\x01 \x01(\t\x12\x14\n\x0c\x61sset_number\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0b\n\x03log\x18\x04 \x01(\t\"5\n\x03log\x12\x0f\n\x07\x61pi_log\x18\x01 \x01(\t\x12\x0e\n\x06\x64\x62_log\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"\x17\n\x07\x61pi_log\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x16\n\x06\x64\x62_log\x12\x0c\n\x04text\x18\x01 \x01(\t2f\n\x05s4api\x12(\n\x06\x63reate\x12\x12.asset.assetInputs\x1a\n.asset.log\x12\x33\n\x07\x64isplay\x12\x12.asset.assetNumber\x1a\x14.asset.assetResponse20\n\x05\x44\x42\x61pi\x12\'\n\x06update\x12\x0e.asset.api_log\x1a\r.asset.db_logb\x06proto3')
)




_ASSETNUMBER = _descriptor.Descriptor(
  name='assetNumber',
  full_name='asset.assetNumber',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='asset.assetNumber.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=56,
)


_ASSETINPUTS = _descriptor.Descriptor(
  name='assetInputs',
  full_name='asset.assetInputs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='company_code', full_name='asset.assetInputs.company_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='asset_number', full_name='asset.assetInputs.asset_number', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='asset.assetInputs.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=136,
)


_ASSETRESPONSE = _descriptor.Descriptor(
  name='assetResponse',
  full_name='asset.assetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='company_code', full_name='asset.assetResponse.company_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='asset_number', full_name='asset.assetResponse.asset_number', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='asset.assetResponse.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='log', full_name='asset.assetResponse.log', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=231,
)


_LOG = _descriptor.Descriptor(
  name='log',
  full_name='asset.log',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='api_log', full_name='asset.log.api_log', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='db_log', full_name='asset.log.db_log', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='asset.log.error', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=286,
)


_API_LOG = _descriptor.Descriptor(
  name='api_log',
  full_name='asset.api_log',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='asset.api_log.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=311,
)


_DB_LOG = _descriptor.Descriptor(
  name='db_log',
  full_name='asset.db_log',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='asset.db_log.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=313,
  serialized_end=335,
)

DESCRIPTOR.message_types_by_name['assetNumber'] = _ASSETNUMBER
DESCRIPTOR.message_types_by_name['assetInputs'] = _ASSETINPUTS
DESCRIPTOR.message_types_by_name['assetResponse'] = _ASSETRESPONSE
DESCRIPTOR.message_types_by_name['log'] = _LOG
DESCRIPTOR.message_types_by_name['api_log'] = _API_LOG
DESCRIPTOR.message_types_by_name['db_log'] = _DB_LOG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

assetNumber = _reflection.GeneratedProtocolMessageType('assetNumber', (_message.Message,), dict(
  DESCRIPTOR = _ASSETNUMBER,
  __module__ = 'createAsset_pb2'
  # @@protoc_insertion_point(class_scope:asset.assetNumber)
  ))
_sym_db.RegisterMessage(assetNumber)

assetInputs = _reflection.GeneratedProtocolMessageType('assetInputs', (_message.Message,), dict(
  DESCRIPTOR = _ASSETINPUTS,
  __module__ = 'createAsset_pb2'
  # @@protoc_insertion_point(class_scope:asset.assetInputs)
  ))
_sym_db.RegisterMessage(assetInputs)

assetResponse = _reflection.GeneratedProtocolMessageType('assetResponse', (_message.Message,), dict(
  DESCRIPTOR = _ASSETRESPONSE,
  __module__ = 'createAsset_pb2'
  # @@protoc_insertion_point(class_scope:asset.assetResponse)
  ))
_sym_db.RegisterMessage(assetResponse)

log = _reflection.GeneratedProtocolMessageType('log', (_message.Message,), dict(
  DESCRIPTOR = _LOG,
  __module__ = 'createAsset_pb2'
  # @@protoc_insertion_point(class_scope:asset.log)
  ))
_sym_db.RegisterMessage(log)

api_log = _reflection.GeneratedProtocolMessageType('api_log', (_message.Message,), dict(
  DESCRIPTOR = _API_LOG,
  __module__ = 'createAsset_pb2'
  # @@protoc_insertion_point(class_scope:asset.api_log)
  ))
_sym_db.RegisterMessage(api_log)

db_log = _reflection.GeneratedProtocolMessageType('db_log', (_message.Message,), dict(
  DESCRIPTOR = _DB_LOG,
  __module__ = 'createAsset_pb2'
  # @@protoc_insertion_point(class_scope:asset.db_log)
  ))
_sym_db.RegisterMessage(db_log)



_S4API = _descriptor.ServiceDescriptor(
  name='s4api',
  full_name='asset.s4api',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=337,
  serialized_end=439,
  methods=[
  _descriptor.MethodDescriptor(
    name='create',
    full_name='asset.s4api.create',
    index=0,
    containing_service=None,
    input_type=_ASSETINPUTS,
    output_type=_LOG,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='display',
    full_name='asset.s4api.display',
    index=1,
    containing_service=None,
    input_type=_ASSETNUMBER,
    output_type=_ASSETRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_S4API)

DESCRIPTOR.services_by_name['s4api'] = _S4API


_DBAPI = _descriptor.ServiceDescriptor(
  name='DBapi',
  full_name='asset.DBapi',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=441,
  serialized_end=489,
  methods=[
  _descriptor.MethodDescriptor(
    name='update',
    full_name='asset.DBapi.update',
    index=0,
    containing_service=None,
    input_type=_API_LOG,
    output_type=_DB_LOG,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DBAPI)

DESCRIPTOR.services_by_name['DBapi'] = _DBAPI

# @@protoc_insertion_point(module_scope)
