version: "2"
services:

  frontend:
    image: ericwudocker01/demojam2019_frontend
    ports:
      - "5000:5000"

  account:
    image: ericwudocker01/demojam2019_account
    ports:
      - "50050:50050"

  db_server:
    image: ericwudocker01/demojam2019_asset
    links:
      - db
    ports:
      - "8001:8001"


  db:
    image: ericwudocker01/db:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: helloworld01
    volumes:
      - .:/docker-entrypoint-initdb.d/:ro

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  assetcreation:
    image: ericwudocker01/demojam2019_asset
    ports:
      - "50051:50051"


