apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "asset.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "asset.name" . }}
    helm.sh/chart: {{ include "asset.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.Asset.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "asset.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "asset.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.Asset.containername }}
          image: "{{ .Values.Asset.image.repository }}:{{ .Values.Asset.image.tag }}"
          imagePullPolicy: {{ .Values.Asset.image.pullPolicy }}
          ports:
          - name: grpc
            containerPort: {{ .Values.Asset.containerPort }}
          env:
          - name: PORT
            value: "50051"
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50051"]
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50051"]

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
