apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
{{ include "asset.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      name: http
  selector:
    app.kubernetes.io/name: {{ include "asset.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
